### ISSUE TITLE
Differences with scBasset

### ISSUE THREAD

**Issue by GlancerZ** [biomed-AI/SANGO#1]
I noticed that your work's stage 1 is similar to the scBasset framework. However, compared to scBasset, SANGO uses CA-CNN. I would like to know what other differences exist between the two, and how do you combine the peaks' embedding to cell's embedding.

**Comment by cquzys** [comment]
Thanks for your comments. Our research method consists of a two-stage model, primarily aiming at cell type classification, with fundamental differences in task setup compared to scBasset. We employed the Graph Transformer technique for cell classification, which is essentially a supervised learning problem, in contrast to the unsupervised learning approach used by scBasset. Additionally, we leverage the edge attention mechanism of the Graph Transformer to identify unknown cell types effectively, and this has been successfully validated on cancer datasets. If you have any questions beyond the scope of the software, please feel free to contact me at [zengys@cqu.edu.cn.]
